const FETCH_USER = "FETCH_USER"
const CREATE_USER = "CREATE_USER"
const LOGIN_USER = "LOGIN_USER"

const INPUT_USER_NAME = "INPUT_USER_NAME"
const INPUT_USER_EMAIL = "INPUT_USER_EMAIL"
const INPUT_USER_PASSWORD = "INPUT_USER_PASSWORD"

export default {
  FETCH_USER,
  CREATE_USER,
  LOGIN_USER,
  INPUT_USER_NAME,
  INPUT_USER_EMAIL,
  INPUT_USER_PASSWORD
};
